---

- name: update cache
  apt:
    update_cache: yes

- name: install pip
  apt:
    name: python3-pip
    state: present

- name: incase Ansible is using wrong python interpreter
  pip:
    name: docker
    state: present

- name: copy jenkins dockerfile
  copy:
    src: ./jenkins/Dockerfile
    dest: /tmp/
    owner: ubuntu

- name: Build Jenkins Image
  docker_image:
    build:
      path: /tmp/
    name: jenkins
    tag: latest
    source: build

- name: Run jenkins container
  docker_container:
    name: jenkins
    image: jenkins
    state: started
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
